import DirectionProvider from '@/providers/DirectionProvider';
import StoreProvider from '@/providers/StoreProvider';
import MuiThemeProvider from '@/providers/MuiThemeProvider';
import { SessionProvider } from 'next-auth/react';
import ApolloClientProvider from '@/providers/ApolloClientProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <StoreProvider>
          <SessionProvider>
            <ApolloClientProvider>
              <DirectionProvider>
                <MuiThemeProvider>{children}</MuiThemeProvider>
              </DirectionProvider>
            </ApolloClientProvider>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}

