import DirectionProvider from '@/providers/DirectionProvider';
import StoreProvider from '@/providers/StoreProvider';
import MuiThemeProvider from '@/providers/MuiThemeProvider';
import { SessionProvider } from 'next-auth/react';
import './globals.css';
import 'swiper/css';
import 'swiper/css/navigation';
import AOSProvider from '@/providers/AOSProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <StoreProvider>
          <SessionProvider
            refetchInterval={process.env.REFETCH_SESSION_INTERVAL_TIME}
          >
            <DirectionProvider>
              <MuiThemeProvider>
                <AOSProvider>{children}</AOSProvider>
              </MuiThemeProvider>
            </DirectionProvider>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
