import StoreProvider from '@/providers/StoreProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider> {children}</StoreProvider>
      </body>
    </html>
  );
}

